<#
.SYNOPSIS
    Detects breaking changes in uncommitted code across all PayrollEngine APIs
    and documents them in RELEASE_NOTES.md.

.DESCRIPTION
    Compares the current (uncommitted) state against the last Git commit for:
      0. Swagger Generation       -- regenerate swagger.json from Backend build
      1. REST API (Provider)      -- swagger.json diff
      2. Backend API Models       -- public .NET API surface diff
      3. Scripting API (Regulator) -- public .NET API surface diff
      4. Client Services (Automator) -- public .NET API surface diff
      5. RELEASE_NOTES.md         -- append breaking changes to release notes

    No external tools required -- uses PowerShell + dotnet SDK only.
    Compatible with PowerShell 5.1+ and .NET 9/10 assemblies.

.PARAMETER ReposRoot
    Root folder containing all PayrollEngine repositories.

.PARAMETER BaselineRef
    Git ref to compare against (default: HEAD).

.PARAMETER ReportPath
    Optional path for the output report file.

.PARAMETER SwaggerJsonPath
    Optional path to a pre-generated swagger.json file. When provided,
    the script skips Swashbuckle CLI generation and uses this file
    directly for the REST API diff. Useful in CI where swagger.json
    has already been generated by a prior build step.

.PARAMETER ConfirmReleaseNotes
    Prompts for confirmation before updating RELEASE_NOTES.md.
    Default behavior (without this switch) is automatic update.

.PARAMETER SkipReleaseNotes
    Skips the RELEASE_NOTES.md update entirely.

.EXAMPLE
    .\Update-BreakingChanges.ps1
    .\Update-BreakingChanges.ps1 -BaselineRef "v0.9.0" -ReportPath ".\breaking-changes.md"
    .\Update-BreakingChanges.ps1 -ConfirmReleaseNotes
    .\Update-BreakingChanges.ps1 -SkipReleaseNotes
    .\Update-BreakingChanges.ps1 -SwaggerJsonPath "docs\swagger.json"
#>

[CmdletBinding()]
param(
    [string]$ReposRoot = (Resolve-Path "$PSScriptRoot\..\..\..").Path,
    [string]$BaselineRef = "HEAD",
    [string]$ReportPath,
    [string]$SwaggerJsonPath,
    [switch]$ConfirmReleaseNotes,
    [switch]$SkipReleaseNotes
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# -- Configuration ------------------------------------------------------------

$config = @{
    RestApi = @{
        Repo        = "$ReposRoot\PayrollEngine"
        SwaggerPath = "docs\swagger.json"
    }
    BackendServer = @{
        Repo        = "$ReposRoot\PayrollEngine.Backend"
        Project     = "Backend.Server\PayrollEngine.Backend.Server.csproj"
        Assembly    = "PayrollEngine.Backend.Server.dll"
        SwaggerDoc  = "PayrollEngineBackendAPI"
    }
    BackendApi = @{
        Repo     = "$ReposRoot\PayrollEngine.Backend"
        Projects = @("PayrollEngine.Api.Model", "PayrollEngine.Domain.Scripting")
    }
    ScriptingApi = @{
        Repo     = "$ReposRoot\PayrollEngine.Client.Scripting"
        Projects = @("PayrollEngine.Client.Scripting")
    }
    ClientServices = @{
        Repo     = "$ReposRoot\PayrollEngine.Client.Services"
        Projects = @("PayrollEngine.Client.Services")
    }
}

# -- Helpers -------------------------------------------------------------------

$script:report = [System.Collections.Generic.List[string]]::new()
$script:breakingCount = 0
$script:warningCount = 0
$script:currentSectionKey = ""
$script:sectionBreaks = @{}

# RELEASE_NOTES.md section mapping
$script:releaseNotesPath = "$ReposRoot\PayrollEngine\RELEASE_NOTES.md"
$script:releaseNotesMap = @{
    RestApi        = @{ Header = "Backend";          Url = "https://github.com/Payroll-Engine/PayrollEngine.Backend"; IsLibrary = $false }
    BackendApi     = @{ Header = "Backend";          Url = "https://github.com/Payroll-Engine/PayrollEngine.Backend"; IsLibrary = $false }
    ScriptingApi   = @{ Header = "Client Scripting"; Url = "https://github.com/Payroll-Engine/PayrollEngine.Client.Scripting"; IsLibrary = $true }
    ClientServices = @{ Header = "Client Services"; Url = "https://github.com/Payroll-Engine/PayrollEngine.Client.Services"; IsLibrary = $true }
}

function Write-Section([string]$title) {
    $line = "-" * 70
    Write-Host ("`n" + $line) -ForegroundColor DarkGray
    Write-Host ("  " + $title) -ForegroundColor Cyan
    Write-Host $line -ForegroundColor DarkGray
    $script:report.Add("`n## " + $title + "`n")
}

function Write-Breaking([string]$message) {
    Write-Host "  BREAKING: $message" -ForegroundColor Red
    $script:report.Add("- **BREAKING:** $message")
    $script:breakingCount++

    if ($script:currentSectionKey) {
        if (-not $script:sectionBreaks.ContainsKey($script:currentSectionKey)) {
            $script:sectionBreaks[$script:currentSectionKey] = [System.Collections.Generic.List[string]]::new()
        }
        $script:sectionBreaks[$script:currentSectionKey].Add($message)
    }
}

function Write-Warn([string]$message) {
    Write-Host "  WARNING:  $message" -ForegroundColor Yellow
    $script:report.Add("- WARNING: $message")
    $script:warningCount++
}

function Write-Ok([string]$message) {
    Write-Host "  OK:      $message" -ForegroundColor Green
}

function Get-SafeProperty($obj, [string]$name, $default = $null) {
    if ($null -eq $obj) { return $default }
    $prop = $obj.PSObject.Properties[$name]
    if ($null -eq $prop) { return $default }
    return $prop.Value
}

function Invoke-Git {
    param([string]$WorkDir, [string[]]$Arguments)
    $pinfo = New-Object System.Diagnostics.ProcessStartInfo
    $pinfo.FileName = "git"
    $pinfo.Arguments = $Arguments -join " "
    $pinfo.WorkingDirectory = $WorkDir
    $pinfo.RedirectStandardOutput = $true
    $pinfo.RedirectStandardError = $true
    $pinfo.UseShellExecute = $false
    $pinfo.CreateNoWindow = $true
    $proc = [System.Diagnostics.Process]::Start($pinfo)
    $stdout = $proc.StandardOutput.ReadToEnd()
    $null = $proc.StandardError.ReadToEnd()
    $proc.WaitForExit()
    return @{ Output = $stdout; ExitCode = $proc.ExitCode }
}

function Get-GitFileContent([string]$repoPath, [string]$filePath, [string]$ref) {
    $gitPath = $filePath -replace '\\', '/'
    $result = Invoke-Git -WorkDir $repoPath -Arguments @("show", "${ref}:${gitPath}")
    if ($result.ExitCode -ne 0) { return $null }
    return $result.Output
}

function Test-HasUncommittedChanges([string]$repoPath) {
    $result = Invoke-Git -WorkDir $repoPath -Arguments @("status", "--porcelain")
    return ($result.ExitCode -eq 0 -and $result.Output.Trim().Length -gt 0)
}

# -- 0. Swagger generation -----------------------------------------------------

function Update-SwaggerJson {
    Write-Section "Swagger Generation"

    $swaggerTarget = Join-Path $config.RestApi.Repo $config.RestApi.SwaggerPath

    if ($SwaggerJsonPath) {
        $resolvedPath = Resolve-Path $SwaggerJsonPath -ErrorAction SilentlyContinue
        if (-not $resolvedPath) {
            Write-Warn "pre-generated swagger.json not found: $SwaggerJsonPath"
            return
        }

        $swaggerDir = Split-Path $swaggerTarget -Parent
        if (-not (Test-Path $swaggerDir)) {
            New-Item -ItemType Directory -Path $swaggerDir -Force | Out-Null
        }

        Copy-Item -Path $resolvedPath.Path -Destination $swaggerTarget -Force
        Write-Ok "using pre-generated swagger.json from $($resolvedPath.Path)"
        return
    }

    $backendRepo = $config.BackendServer.Repo
    $serverCsproj = Join-Path $backendRepo $config.BackendServer.Project
    $swaggerDoc = $config.BackendServer.SwaggerDoc

    if (-not (Test-Path $serverCsproj)) {
        Write-Warn "server project not found: $serverCsproj"
        return
    }

    $swashCheck = dotnet tool list -g 2>&1
    $hasSwash = @($swashCheck) | Where-Object { $_ -match "swashbuckle" }
    if (-not $hasSwash) {
        Write-Host "  installing Swashbuckle CLI..." -ForegroundColor DarkGray
        $installOut = dotnet tool install -g Swashbuckle.AspNetCore.Cli 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Warn "failed to install Swashbuckle CLI -- swagger.json will not be regenerated"
            return
        }
    }

    Write-Host "  building Backend server..." -ForegroundColor DarkGray
    $buildOut = dotnet build $serverCsproj -c Release 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Warn "backend build failed -- swagger.json will not be regenerated"
        return
    }

    $serverDir = Split-Path $serverCsproj -Parent
    $assemblyName = $config.BackendServer.Assembly
    $assembly = Get-ChildItem -Path $serverDir -Filter $assemblyName -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match "bin[\\/]Release" } |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1

    if (-not $assembly) {
        Write-Warn "server assembly not found: $assemblyName"
        return
    }

    Write-Host "  generating swagger.json..." -ForegroundColor DarkGray
    $swaggerDir = Split-Path $swaggerTarget -Parent
    if (-not (Test-Path $swaggerDir)) {
        New-Item -ItemType Directory -Path $swaggerDir -Force | Out-Null
    }

    $pinfo = New-Object System.Diagnostics.ProcessStartInfo
    $pinfo.FileName = "swagger"
    $pinfo.Arguments = "tofile --output `"$swaggerTarget`" `"$($assembly.FullName)`" $swaggerDoc"
    $pinfo.RedirectStandardOutput = $true
    $pinfo.RedirectStandardError = $true
    $pinfo.UseShellExecute = $false
    $pinfo.CreateNoWindow = $true
    $proc = [System.Diagnostics.Process]::Start($pinfo)
    $stdout = $proc.StandardOutput.ReadToEnd()
    $stderr = $proc.StandardError.ReadToEnd()
    $proc.WaitForExit()

    if ($proc.ExitCode -ne 0) {
        Write-Warn "swagger generation failed: $stderr"
        return
    }

    Write-Ok "swagger.json regenerated from $($assembly.Name)"
}

# -- 1. REST API -- swagger.json comparison ------------------------------------

function Compare-SwaggerBreakingChanges {
    Write-Section "REST API (Provider) -- swagger.json"

    $repo = $config.RestApi.Repo
    $swaggerRel = $config.RestApi.SwaggerPath
    $swaggerFull = Join-Path $repo $swaggerRel

    if (-not (Test-Path $swaggerFull)) {
        Write-Warn "swagger.json not found: $swaggerFull"
        return
    }

    if (-not (Test-HasUncommittedChanges $repo)) {
        Write-Ok "no uncommitted changes in $repo"
        return
    }

    $baselineJson = Get-GitFileContent $repo $swaggerRel $BaselineRef
    if (-not $baselineJson) {
        Write-Warn "cannot read $swaggerRel from $BaselineRef"
        return
    }

    $baseline = $baselineJson | ConvertFrom-Json
    $current  = Get-Content $swaggerFull -Raw | ConvertFrom-Json

    $found = $false

    $baselinePaths = @{}
    $bPaths = Get-SafeProperty $baseline 'paths'
    if ($bPaths) { $bPaths.PSObject.Properties | ForEach-Object { $baselinePaths[$_.Name] = $_.Value } }
    $currentPaths = @{}
    $cPaths = Get-SafeProperty $current 'paths'
    if ($cPaths) { $cPaths.PSObject.Properties | ForEach-Object { $currentPaths[$_.Name] = $_.Value } }

    foreach ($path in $baselinePaths.Keys) {
        if (-not $currentPaths.ContainsKey($path)) {
            Write-Breaking "endpoint removed: $path"
            $found = $true
            continue
        }

        $baseMethods = $baselinePaths[$path].PSObject.Properties | Where-Object { $_.Name -in @('get','post','put','delete','patch') }
        $currMethods = @{}
        $currentPaths[$path].PSObject.Properties | Where-Object { $_.Name -in @('get','post','put','delete','patch') } |
            ForEach-Object { $currMethods[$_.Name] = $_.Value }

        foreach ($method in $baseMethods) {
            if (-not $currMethods.ContainsKey($method.Name)) {
                Write-Breaking "method removed: $($method.Name.ToUpper()) $path"
                $found = $true
                continue
            }

            $baseOp = $method.Value
            $currOp = $currMethods[$method.Name]

            $baseParams = @()
            $bpVal = Get-SafeProperty $baseOp 'parameters'
            if ($bpVal) { $baseParams = @($bpVal) }
            $currParams = @()
            $cpVal = Get-SafeProperty $currOp 'parameters'
            if ($cpVal) { $currParams = @($cpVal) }

            foreach ($bp in $baseParams) {
                $paramKey = $bp.name + "|" + $bp.in
                $match = $currParams | Where-Object { ($_.name + "|" + $_.in) -eq $paramKey }
                if (-not $match) {
                    Write-Breaking "parameter removed: $($bp.name) ($($bp.in)) from $($method.Name.ToUpper()) $path"
                    $found = $true
                }
                elseif ((Get-SafeProperty $match 'required') -eq $true -and (Get-SafeProperty $bp 'required') -ne $true) {
                    Write-Breaking "parameter now required: $($bp.name) in $($method.Name.ToUpper()) $path"
                    $found = $true
                }
            }

            foreach ($cp in $currParams) {
                $paramKey = $cp.name + "|" + $cp.in
                $match = $baseParams | Where-Object { ($_.name + "|" + $_.in) -eq $paramKey }
                if (-not $match -and (Get-SafeProperty $cp 'required') -eq $true) {
                    Write-Breaking "new required parameter: $($cp.name) ($($cp.in)) in $($method.Name.ToUpper()) $path"
                    $found = $true
                }
            }

            $baseResp = Get-SafeProperty $baseOp 'responses'
            $currResp = Get-SafeProperty $currOp 'responses'
            if ($baseResp -and $currResp) {
                $baseResponses = $baseResp.PSObject.Properties.Name
                $currResponses = $currResp.PSObject.Properties.Name
                foreach ($code in $baseResponses) {
                    if ($code -match "^2\d{2}" -and $code -notin $currResponses) {
                        Write-Breaking "success response removed: $code from $($method.Name.ToUpper()) $path"
                        $found = $true
                    }
                }
            }
        }
    }

    foreach ($path in $currentPaths.Keys) {
        if (-not $baselinePaths.ContainsKey($path)) {
            Write-Ok "new endpoint: $path"
        }
    }

    $schemaKey = if (Get-SafeProperty $baseline 'components') { "components" } else { "definitions" }
    $baseSchemas = @{}
    $currSchemas = @{}

    $baseComp = Get-SafeProperty $baseline 'components'
    if ($schemaKey -eq "components" -and $baseComp -and (Get-SafeProperty $baseComp 'schemas')) {
        (Get-SafeProperty $baseComp 'schemas').PSObject.Properties | ForEach-Object { $baseSchemas[$_.Name] = $_.Value }
    }
    elseif ($schemaKey -eq "definitions" -and (Get-SafeProperty $baseline 'definitions')) {
        (Get-SafeProperty $baseline 'definitions').PSObject.Properties | ForEach-Object { $baseSchemas[$_.Name] = $_.Value }
    }

    $currComp = Get-SafeProperty $current 'components'
    if ($schemaKey -eq "components" -and $currComp -and (Get-SafeProperty $currComp 'schemas')) {
        (Get-SafeProperty $currComp 'schemas').PSObject.Properties | ForEach-Object { $currSchemas[$_.Name] = $_.Value }
    }
    elseif ($schemaKey -eq "definitions" -and (Get-SafeProperty $current 'definitions')) {
        (Get-SafeProperty $current 'definitions').PSObject.Properties | ForEach-Object { $currSchemas[$_.Name] = $_.Value }
    }

    foreach ($name in $baseSchemas.Keys) {
        if (-not $currSchemas.ContainsKey($name)) {
            Write-Breaking "schema removed: $name"
            $found = $true
            continue
        }

        $baseProps = @{}
        $bsPropVal = Get-SafeProperty $baseSchemas[$name] 'properties'
        if ($bsPropVal) { $bsPropVal.PSObject.Properties | ForEach-Object { $baseProps[$_.Name] = $_.Value } }
        $currProps = @{}
        $csPropVal = Get-SafeProperty $currSchemas[$name] 'properties'
        if ($csPropVal) { $csPropVal.PSObject.Properties | ForEach-Object { $currProps[$_.Name] = $_.Value } }

        foreach ($prop in $baseProps.Keys) {
            if (-not $currProps.ContainsKey($prop)) {
                Write-Breaking "property removed: $($name).$prop"
                $found = $true
            }
            else {
                $baseType = Get-SafeProperty $baseProps[$prop] 'type'
                $currType = Get-SafeProperty $currProps[$prop] 'type'
                if ($baseType -and $currType -and $baseType -ne $currType) {
                    Write-Breaking "property type changed: $($name).$prop ($baseType -> $currType)"
                    $found = $true
                }
            }
        }

        $baseRequired = @()
        $baseReqVal = Get-SafeProperty $baseSchemas[$name] 'required'
        if ($baseReqVal) { $baseRequired = @($baseReqVal) }
        $currRequired = @()
        $currReqVal = Get-SafeProperty $currSchemas[$name] 'required'
        if ($currReqVal) { $currRequired = @($currReqVal) }

        $newRequired = $currRequired | Where-Object { $_ -notin $baseRequired }
        foreach ($req in $newRequired) {
            Write-Breaking "property now required: $($name).$req"
            $found = $true
        }
    }

    if (-not $found) {
        Write-Ok "no breaking changes detected in REST API"
        $script:report.Add("- No breaking changes detected.")
    }
}

# -- 2/3/4. .NET API surface comparison ----------------------------------------

function Initialize-ApiExtractorProject {
    $toolDir = Join-Path ([System.IO.Path]::GetTempPath()) "bc-api-extractor"
    $csproj  = Join-Path $toolDir "ApiExtractor.csproj"
    $program = Join-Path $toolDir "Program.cs"

    if (Test-Path $toolDir) {
        Remove-Item $toolDir -Recurse -Force -ErrorAction SilentlyContinue
    }
    New-Item -ItemType Directory -Path $toolDir -Force | Out-Null

    $sdkVersion = dotnet --version 2>$null
    if ($sdkVersion -match "^10\.") { $tfm = "net10.0"; $pkgVer = "10.0.*" }
    elseif ($sdkVersion -match "^9\.") { $tfm = "net9.0"; $pkgVer = "9.0.*" }
    else { $tfm = "net8.0"; $pkgVer = "9.0.*" }

    @"
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$tfm</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="$pkgVer" />
  </ItemGroup>
</Project>
"@ | Set-Content -Path $csproj -Encoding UTF8

    @'
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

var assemblyPath = args[0];
var signatures = new SortedSet<string>();

var assemblyDir = Path.GetDirectoryName(Path.GetFullPath(assemblyPath))!;
var runtimeDir = RuntimeEnvironment.GetRuntimeDirectory();
var resolver = new PathAssemblyResolver(
    Directory.GetFiles(runtimeDir, "*.dll")
        .Concat(Directory.GetFiles(assemblyDir, "*.dll"))
        .Distinct());

using var mlc = new MetadataLoadContext(resolver);
var assembly = mlc.LoadFromAssemblyPath(Path.GetFullPath(assemblyPath));

foreach (var type in assembly.GetExportedTypes().OrderBy(t => t.FullName))
{
    var typeKind = type.IsInterface ? "interface" :
                   type.IsEnum ? "enum" :
                   type.IsValueType ? "struct" :
                   (type.IsAbstract && type.IsSealed) ? "static class" :
                   type.IsAbstract ? "abstract class" : "class";

    var baseName = type.BaseType != null && type.BaseType.FullName != "System.Object"
        ? " : " + type.BaseType.Name : "";

    signatures.Add($"{typeKind} {type.FullName}{baseName}");

    if (type.IsEnum)
    {
        foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static).OrderBy(f => f.Name))
        {
            var rawValue = field.GetRawConstantValue();
            signatures.Add($"  {type.FullName}.{field.Name} = {rawValue}");
        }
        continue;
    }

    var flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

    foreach (var ctor in type.GetConstructors(BindingFlags.Public | BindingFlags.Instance).OrderBy(c => c.ToString()))
    {
        var p = string.Join(", ", ctor.GetParameters().Select(x => $"{x.ParameterType.Name} {x.Name}"));
        signatures.Add($"  {type.Name}({p})");
    }

    foreach (var m in type.GetMethods(flags).Where(m => !m.IsSpecialName).OrderBy(m => m.Name).ThenBy(m => m.ToString()))
    {
        var s = m.IsStatic ? "static " : "";
        var p = string.Join(", ", m.GetParameters().Select(x => $"{x.ParameterType.Name} {x.Name}"));
        signatures.Add($"  {s}{m.ReturnType.Name} {type.FullName}.{m.Name}({p})");
    }

    foreach (var prop in type.GetProperties(flags).OrderBy(p => p.Name))
    {
        var s = (prop.GetMethod?.IsStatic ?? prop.SetMethod?.IsStatic ?? false) ? "static " : "";
        var acc = new List<string>();
        if (prop.CanRead) acc.Add("get");
        if (prop.CanWrite) acc.Add("set");
        signatures.Add($"  {s}{prop.PropertyType.Name} {type.FullName}.{prop.Name} {{ {string.Join("; ", acc)} }}");
    }

    foreach (var evt in type.GetEvents(flags).OrderBy(e => e.Name))
    {
        signatures.Add($"  event {evt.EventHandlerType?.Name} {type.FullName}.{evt.Name}");
    }
}

foreach (var sig in signatures)
    Console.WriteLine(sig);
'@ | Set-Content -Path $program -Encoding UTF8

    Write-Host "  preparing API extractor tool..." -ForegroundColor DarkGray
    $buildOut = dotnet build $csproj -c Release 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Warn "failed to build API extractor: $buildOut"
        return $null
    }

    return $toolDir
}

function Get-PublicApiSurface([string]$assemblyPath, [string]$toolDir) {
    if (-not (Test-Path $assemblyPath)) { return @() }
    if (-not $toolDir -or -not (Test-Path $toolDir)) { return @() }

    $csproj = Join-Path $toolDir "ApiExtractor.csproj"

    $pinfo = New-Object System.Diagnostics.ProcessStartInfo
    $pinfo.FileName = "dotnet"
    $pinfo.Arguments = "run --project `"$csproj`" -c Release --no-build -- `"$assemblyPath`""
    $pinfo.RedirectStandardOutput = $true
    $pinfo.RedirectStandardError = $true
    $pinfo.UseShellExecute = $false
    $pinfo.CreateNoWindow = $true
    $proc = [System.Diagnostics.Process]::Start($pinfo)
    $stdout = $proc.StandardOutput.ReadToEnd()
    $null = $proc.StandardError.ReadToEnd()
    $proc.WaitForExit()

    if ($proc.ExitCode -ne 0) {
        Write-Warn "API extraction failed for $assemblyPath"
        return @()
    }

    $lines = @($stdout -split "`n") | ForEach-Object { $_.TrimEnd("`r") } | Where-Object {
        $_ -match "^(class|interface|enum|struct|static class|abstract class|  )"
    }
    return @($lines)
}

function Compare-DotNetApiSurface {
    param(
        [string]$Label,
        [string]$RepoPath,
        [string[]]$ProjectNames,
        [string]$ToolDir
    )

    Write-Section "$Label"

    if (-not (Test-Path $RepoPath)) {
        Write-Warn "repository not found: $RepoPath"
        return
    }

    if (-not (Test-HasUncommittedChanges $RepoPath)) {
        Write-Ok "no uncommitted changes in $RepoPath"
        return
    }

    foreach ($project in $ProjectNames) {
        Write-Host "`n  Analyzing: $project" -ForegroundColor DarkCyan

        $csproj = Get-ChildItem -Path $RepoPath -Filter "$project.csproj" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $csproj) {
            Write-Warn "project file not found: $project.csproj"
            continue
        }

        Write-Host "  building current state..." -ForegroundColor DarkGray
        $currentBuildOut = Join-Path ([System.IO.Path]::GetTempPath()) "bc-current-$project"
        if (Test-Path $currentBuildOut) { Remove-Item $currentBuildOut -Recurse -Force }

        $buildOut = dotnet publish $csproj.FullName -c Release -o $currentBuildOut 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Warn "build failed for current state of $project"
            continue
        }

        $currentDll = Join-Path $currentBuildOut "$project.dll"
        if (-not (Test-Path $currentDll)) {
            Write-Warn "assembly not found after build: $currentDll"
            continue
        }

        $currentApi = @(Get-PublicApiSurface $currentDll $ToolDir)

        # -- Step 2: build baseline from git archive (no working tree changes) --
        Write-Host "  building baseline ($BaselineRef) via git archive..." -ForegroundColor DarkGray
        $baselineApi = @()
        $baselineSrcDir = Join-Path ([System.IO.Path]::GetTempPath()) "bc-baseline-src-$project"
        $baselineBuildOut = Join-Path ([System.IO.Path]::GetTempPath()) "bc-baseline-$project"
        if (Test-Path $baselineSrcDir) { Remove-Item $baselineSrcDir -Recurse -Force }
        if (Test-Path $baselineBuildOut) { Remove-Item $baselineBuildOut -Recurse -Force }
        New-Item -ItemType Directory -Path $baselineSrcDir -Force | Out-Null

        # extract baseline source into temp dir (safe, no stash)
        $pinfo = New-Object System.Diagnostics.ProcessStartInfo
        $pinfo.FileName = "git"
        $pinfo.Arguments = "archive $BaselineRef"
        $pinfo.WorkingDirectory = $RepoPath
        $pinfo.RedirectStandardOutput = $true
        $pinfo.RedirectStandardError = $true
        $pinfo.UseShellExecute = $false
        $pinfo.CreateNoWindow = $true
        $archiveProc = [System.Diagnostics.Process]::Start($pinfo)
        $tarFile = Join-Path $baselineSrcDir "archive.tar"
        # read binary tar stream to file
        $fs = [System.IO.File]::Create($tarFile)
        $archiveProc.StandardOutput.BaseStream.CopyTo($fs)
        $fs.Close()
        $null = $archiveProc.StandardError.ReadToEnd()
        $archiveProc.WaitForExit()

        if ($archiveProc.ExitCode -eq 0 -and (Test-Path $tarFile) -and (Get-Item $tarFile).Length -gt 0) {
            # extract tar
            $tarPinfo = New-Object System.Diagnostics.ProcessStartInfo
            $tarPinfo.FileName = "tar"
            $tarPinfo.Arguments = "xf `"$tarFile`" -C `"$baselineSrcDir`""
            $tarPinfo.RedirectStandardOutput = $true
            $tarPinfo.RedirectStandardError = $true
            $tarPinfo.UseShellExecute = $false
            $tarPinfo.CreateNoWindow = $true
            $tarProc = [System.Diagnostics.Process]::Start($tarPinfo)
            $null = $tarProc.StandardOutput.ReadToEnd()
            $null = $tarProc.StandardError.ReadToEnd()
            $tarProc.WaitForExit()

            if ($tarProc.ExitCode -eq 0) {
                $baselineCsproj = Get-ChildItem -Path $baselineSrcDir -Filter "$project.csproj" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
                if ($baselineCsproj) {
                    $buildOut = dotnet publish $baselineCsproj.FullName -c Release -o $baselineBuildOut 2>&1
                    if ($LASTEXITCODE -eq 0) {
                        $baselineDll = Join-Path $baselineBuildOut "$project.dll"
                        if (Test-Path $baselineDll) {
                            $baselineApi = @(Get-PublicApiSurface $baselineDll $ToolDir)
                        } else {
                            Write-Warn "baseline assembly not found: $baselineDll"
                        }
                    } else {
                        Write-Warn "baseline build failed for $project"
                    }
                } else {
                    Write-Warn "baseline csproj not found in archive for $project"
                }
            } else {
                Write-Warn "tar extraction failed for baseline archive"
            }
        } else {
            Write-Warn "git archive failed for $BaselineRef -- baseline comparison skipped"
        }

        if (@($currentApi).Count -eq 0 -and @($baselineApi).Count -eq 0) {
            Write-Warn "could not extract API surface for $project"
            continue
        }

        $found = $false

        $removed = @($baselineApi | Where-Object { $_ -notin $currentApi })
        foreach ($sig in $removed) {
            $trimmed = $sig.Trim()
            if (-not $sig.StartsWith("  ")) {
                Write-Breaking "type removed: $trimmed"
            }
            else {
                Write-Breaking "member removed: $trimmed"
            }
            $found = $true
        }

        $added = @($currentApi | Where-Object { $_ -notin $baselineApi })
        $addedTypes = @($added | Where-Object { $_ -and -not $_.StartsWith("  ") })
        $addedMembers = @($added | Where-Object { $_ -and $_.StartsWith("  ") })

        if ($addedTypes.Count -gt 0) {
            Write-Ok "$($addedTypes.Count) new type(s) added"
        }
        if ($addedMembers.Count -gt 0) {
            Write-Ok "$($addedMembers.Count) new member(s) added"
        }

        if (-not $found) {
            Write-Ok "no breaking changes detected in $project"
            $script:report.Add("- No breaking changes detected.")
        }

        Remove-Item $currentBuildOut -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item $baselineBuildOut -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item $baselineSrcDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# -- 5. RELEASE_NOTES.md update ------------------------------------------------

function Format-ForReleaseNotes([string]$message) {
    if ($message -match '^member removed:') {
        $sig = $message.Substring('member removed:'.Length).Trim()
        $sig = [regex]::Replace($sig, '`\d+', '')
        if ($sig -match '(\w+)\.(\w+)\(') {
            return "removed ``$($Matches[1]).$($Matches[2])``"
        }
        if ($sig -match '(\w+)\.(\w+)\s*\{') {
            return "removed ``$($Matches[1]).$($Matches[2])``"
        }
        $clean = $sig -replace '\(.*', ''
        $segments = $clean.Trim() -split '\.'
        if ($segments.Count -ge 2) {
            return "removed ``$($segments[-2]).$($segments[-1])``"
        }
        return "removed member (signature changed)"
    }

    if ($message -match '^type removed:') {
        $sig = $message.Substring('type removed:'.Length).Trim()
        $sig = [regex]::Replace($sig, '`\d+', '')
        $segments = $sig.Trim() -split '\.'
        $typeName = $segments[-1] -replace '\s.*', ''
        return "removed type ``$typeName``"
    }

    return $message
}

function Update-ReleaseNotes {
    if ($SkipReleaseNotes) { return }
    if ($script:sectionBreaks.Count -eq 0) { return }

    $notesPath = $script:releaseNotesPath
    if (-not (Test-Path $notesPath)) {
        Write-Warn "RELEASE_NOTES.md not found: $notesPath"
        return
    }

    $grouped = @{}
    foreach ($key in $script:sectionBreaks.Keys) {
        $map = $script:releaseNotesMap[$key]
        if (-not $map) { continue }
        $header = $map.Header
        if (-not $grouped.ContainsKey($header)) {
            $grouped[$header] = @{
                Url       = $map.Url
                IsLibrary = $map.IsLibrary
                Entries   = [System.Collections.Generic.List[string]]::new()
            }
        }
        foreach ($msg in $script:sectionBreaks[$key]) {
            $formatted = Format-ForReleaseNotes $msg
            $entry = "  - $formatted **breaking change**"
            if ($entry -notin $grouped[$header].Entries) {
                $grouped[$header].Entries.Add($entry)
            }
        }
    }

    if ($grouped.Count -eq 0) { return }

    Write-Section "RELEASE_NOTES.md Update"
    foreach ($header in $grouped.Keys) {
        $info = $grouped[$header]
        Write-Host "  [$header]" -ForegroundColor Cyan
        foreach ($entry in $info.Entries) {
            Write-Host "  $entry" -ForegroundColor DarkGray
        }
    }

    if ($ConfirmReleaseNotes) {
        Write-Host ""
        $answer = Read-Host "  Update RELEASE_NOTES.md with the above entries? (y/N)"
        if ($answer -ne 'y' -and $answer -ne 'Y') {
            Write-Host "  Skipped RELEASE_NOTES.md update." -ForegroundColor Yellow
            return
        }
    }

    $lines = @(Get-Content $notesPath -Encoding UTF8)
    $result = [System.Collections.Generic.List[string]]::new()
    $insertedSections = @{}

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        $result.Add($line)

        foreach ($header in $grouped.Keys) {
            $pattern = "- [$header]("
            if ($line.TrimStart().StartsWith($pattern) -and -not $insertedSections.ContainsKey($header)) {
                foreach ($entry in $grouped[$header].Entries) {
                    $result.Add($entry)
                }
                $insertedSections[$header] = $true
            }
        }
    }

    foreach ($header in $grouped.Keys) {
        if ($insertedSections.ContainsKey($header)) { continue }

        $info = $grouped[$header]
        $sectionHeader = "- [$header]($($info.Url))"

        if ($info.IsLibrary) {
            $libIdx = -1
            for ($i = 0; $i -lt $result.Count; $i++) {
                if ($result[$i] -match '^###\s+Libraries') { $libIdx = $i; break }
            }
            if ($libIdx -ge 0) {
                $insertAt = $libIdx + 1
                while ($insertAt -lt $result.Count -and $result[$insertAt].Trim() -eq '') { $insertAt++ }
                $newLines = @("", $sectionHeader)
                foreach ($entry in $info.Entries) { $newLines += $entry }
                for ($j = $newLines.Count - 1; $j -ge 0; $j--) { $result.Insert($insertAt, $newLines[$j]) }
            }
            else {
                $result.Add("")
                $result.Add("### Libraries")
                $result.Add("")
                $result.Add($sectionHeader)
                foreach ($entry in $info.Entries) { $result.Add($entry) }
            }
        }
        else {
            $libIdx = -1
            for ($i = 0; $i -lt $result.Count; $i++) {
                if ($result[$i] -match '^###\s+Libraries') { $libIdx = $i; break }
            }
            if ($libIdx -ge 0) {
                $newLines = @("", $sectionHeader)
                foreach ($entry in $info.Entries) { $newLines += $entry }
                $newLines += ""
                for ($j = $newLines.Count - 1; $j -ge 0; $j--) { $result.Insert($libIdx, $newLines[$j]) }
            }
            else {
                $result.Add("")
                $result.Add($sectionHeader)
                foreach ($entry in $info.Entries) { $result.Add($entry) }
            }
        }
        $insertedSections[$header] = $true
    }

    $result -join "`n" | Set-Content -Path $notesPath -Encoding UTF8 -NoNewline
    Write-Ok "RELEASE_NOTES.md updated ($($script:breakingCount) entries added)"
    $script:report.Add("`n## RELEASE_NOTES.md`n")
    $script:report.Add("- Updated: $notesPath")
}

# -- Main ----------------------------------------------------------------------
# Exit codes:
#   0  -- no breaking changes detected
#   1  -- breaking changes detected (document in RELEASE_NOTES.md)
#   2  -- infrastructure failure (build, git, or tool error; detection unreliable)

$startTime = Get-Date

try {
    Write-Host "`n  PayrollEngine Breaking Change Detection" -ForegroundColor White
    Write-Host "  Baseline: $BaselineRef | $(Get-Date -Format 'yyyy-MM-dd HH:mm')" -ForegroundColor DarkGray
    $script:report.Add("# PayrollEngine -- Breaking Change Report")
    $script:report.Add("**Baseline:** ``$BaselineRef`` | **Date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm')")

    Update-SwaggerJson

    $script:currentSectionKey = "RestApi"
    Compare-SwaggerBreakingChanges

    $toolDir = Initialize-ApiExtractorProject
    if (-not $toolDir) {
        throw "API extractor project could not be built -- .NET API surface comparison is unavailable."
    }

    $script:currentSectionKey = "BackendApi"
    Compare-DotNetApiSurface `
        -Label "Backend API Models -- public API surface" `
        -RepoPath $config.BackendApi.Repo `
        -ProjectNames $config.BackendApi.Projects `
        -ToolDir $toolDir

    $script:currentSectionKey = "ScriptingApi"
    Compare-DotNetApiSurface `
        -Label "Scripting API (Regulator) -- public API surface" `
        -RepoPath $config.ScriptingApi.Repo `
        -ProjectNames $config.ScriptingApi.Projects `
        -ToolDir $toolDir

    $script:currentSectionKey = "ClientServices"
    Compare-DotNetApiSurface `
        -Label "Client Services (Automator) -- public API surface" `
        -RepoPath $config.ClientServices.Repo `
        -ProjectNames $config.ClientServices.Projects `
        -ToolDir $toolDir

    $script:currentSectionKey = ""

    if ($toolDir -and (Test-Path $toolDir)) {
        Remove-Item $toolDir -Recurse -Force -ErrorAction SilentlyContinue
    }

    Update-ReleaseNotes

    $elapsed = (Get-Date) - $startTime
    Write-Host "`n$("-" * 70)" -ForegroundColor DarkGray

    if ($script:breakingCount -gt 0) {
        Write-Host "  RESULT: $($script:breakingCount) breaking change(s), $($script:warningCount) warning(s)" -ForegroundColor Red
    }
    elseif ($script:warningCount -gt 0) {
        Write-Host "  RESULT: No breaking changes, $($script:warningCount) warning(s)" -ForegroundColor Yellow
    }
    else {
        Write-Host "  RESULT: No breaking changes detected" -ForegroundColor Green
    }
    Write-Host "  Elapsed: $($elapsed.TotalSeconds.ToString('F1'))s" -ForegroundColor DarkGray

    $script:report.Add("`n---")
    $script:report.Add("**Summary:** $($script:breakingCount) breaking change(s), $($script:warningCount) warning(s) | $($elapsed.TotalSeconds.ToString('F1'))s")

    if ($ReportPath) {
        $script:report -join "`n" | Set-Content -Path $ReportPath -Encoding UTF8
        Write-Host "  Report: $ReportPath" -ForegroundColor DarkGray
    }

    if ($script:breakingCount -gt 0) { exit 1 }
    exit 0
}
catch {
    $elapsed = (Get-Date) - $startTime
    Write-Host "`n$("-" * 70)" -ForegroundColor DarkGray
    Write-Host "  RESULT: Infrastructure failure -- detection aborted" -ForegroundColor Magenta
    Write-Host "  ERROR:  $_" -ForegroundColor Magenta
    Write-Host "  Elapsed: $($elapsed.TotalSeconds.ToString('F1'))s" -ForegroundColor DarkGray

    $script:report.Add("`n---")
    $script:report.Add("**Result:** Infrastructure failure -- ``$_``")

    if ($ReportPath) {
        $script:report -join "`n" | Set-Content -Path $ReportPath -Encoding UTF8 -ErrorAction SilentlyContinue
    }

    exit 2
}
