call PayrollConsole RegulationRebuild SimplePayroll SimplePayroll
call PayrollConsole PayrunRebuild SimplePayroll SimplePayrollPayrun1
call PayrollConsole PayrunRebuild SimplePayroll SimplePayrollPayrun2
pause